---
version: '3.8'

services:
  rstudio-server:
    container_name: rstudio-server
    image: dceoy/rstudio-server:latest
    ports:
      - 8787:8787
    volumes:
      - rstudio-server-data:/home/rstudio
    working_dir: /home/rstudio
    entrypoint:
      - /usr/lib/rstudio-server/bin/rserver
    command:
      - --server-daemonize=0
      - --server-app-armor-enabled=0

volumes:
  rstudio-server-data: